rustup 1.72 and minor typo
Today I attempted to use the steps provided but failed, below the logs.
I upgraded to rustup 1.72 and everything is working fine so thought why
not provide a PR for it.

```shell
❯ cargo run --release
info: syncing channel updates for '1.65.0-x86_64-unknown-linux-gnu'
info: latest update on 2022-11-03, rust version 1.65.0 (897e37553 2022-11-02)
error: 'rustc' is not installed for the toolchain '1.65.0-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustc --toolchain 1.65.0-x86_64-unknown-linux-gnu`
error: could not compile `egui_glow`
warning: build failed, waiting for other jobs to finish...
info: syncing channel updates for '1.65.0-x86_64-unknown-linux-gnu'
error: 'rustc' is not installed for the toolchain '1.65.0-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustc --toolchain 1.65.0-x86_64-unknown-linux-gnu`
error: could not compile `atspi`
❯ rustup component add rustc --toolchain 1.65.0-x86_64-unknown-linux-gnu
error: Missing manifest in toolchain '1.65.0-x86_64-unknown-linux-gnu'
```

Note this could be related to my current machine setup. Since 1.65 is
from 10 months ago maybe it's being deprecated soon?